version: "3.7"
services:
  etcd:
    image: soyking/etcd-goreman:3.2.7
    environment:
      - CLIENT_ADDR=etcd
    ports:
      - "2379:2379"
  e3w:
    image: soyking/e3w:latest
    volumes:
      - ./conf/config.default.ini:/app/conf/config.default.ini
    ports:
      - "23790:8080"
    depends_on:
      - etcd