version: "3"

networks:
  loki:

services:
  # 日志存储和解析
  loki:
    image: grafana/loki:2.3.0
    container_name: lpg-loki
    volumes:
      - ./etc/loki/:/etc/loki/
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.3.0
    container_name: lpg-promtail
    volumes:
      - ./etc/promtail/:/etc/promtail/
      - /Users/fuzhifei/Code/go/src/fwds/storage/logs:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: lpg-grafana
    ports:
      - "3000:3000"
    networks:
      - loki