// Code generated by "stringer -type=StatusType"; DO NOT EDIT.

package enum_status

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Normal-1]
	_ = x[Disable - -1]
	_ = x[Del - -2]
}

const (
	_StatusType_name_0 = "DelDisable"
	_StatusType_name_1 = "Normal"
)

var (
	_StatusType_index_0 = [...]uint8{0, 3, 10}
)

func (i StatusType) String() string {
	switch {
	case -2 <= i && i <= -1:
		i -= -2
		return _StatusType_name_0[_StatusType_index_0[i]:_StatusType_index_0[i+1]]
	case i == 1:
		return _StatusType_name_1
	default:
		return "StatusType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
