App:
  Name: fwds                      # 应用名称
  Mode: debug                     # 开发模式, debug, release, test
  Debug: true                     # 是否开启debug
  Version: 1.0.0                  # 版本号
  PprofPort: :5555                # pprof端口号
  Host: www.fwds.com              # 网站域名
  SSL: true                       # 是否开启ssl
  CSRF: true                      # 是否开启csrf

Http: # http 服务
  Addr: :8080
  ReadTimeout: 5
  WriteTimeout: 5

Grpc: # grpc 服务
  Addr: :9090
  ReadTimeout: 5
  WriteTimeout: 5

Mysql:
  Default: # 默认库
    Name: fwds                      # 数据库名称
    Addr: localhost:3306            # 如果是 docker,可以替换为 对应的服务名称，eg: db:3306
    UserName: root                  # 数据库账户名
    Password: 123456                # 数据库密码
    ShowLog: true                   # 是否打印SQL日志
    MaxIdleConn: 10                 # 最大闲置的连接数，0意味着使用默认的大小2， 小于0表示不使用连接池
    MaxOpenConn: 60                 # 最大打开的连接数, 需要小于数据库配置中的max_connections数
    ConnMaxLifeTime: 60m            # 单个连接最大存活时间，建议设置比数据库超时时长(wait_timeout)稍小一些

Cache:
  Driver: "redis"                   # 缓存驱动，可以选memory、redis, 默认redis
  Prefix: "fzf:"                   # cache key前缀，一般为项目名称即可

Redis:
  Addr: 127.0.0.1:6379              # 地址
  Password: "123456"                # 密码
  Db: 0                             # use default DB
  MinIdleConn: 200                  # 最小闲置连接数
  DialTimeout: 60s                  # 连接超时
  ReadTimeout: 500ms                # 读取超时
  WriteTimeout: 500ms               # 写入超时
  PoolSize: 12000                   #
  PoolTimeout: 240                  #

Log:
  Name: fwds
  Development: false                            #是否开发
  DisableCaller: false                          #是否开启堆栈
  DisableStacktrace: false
  Encoding: json                                # json or console
  Level: info                                   # 日志级别，DEBUG, INFO, WARN, ERROR, FATAL
  Writers: file,console                         # 有2个可选项：file,console, 可以两者同时选择输出位置，有2个可选项：file,console。选择file会将日志记录到file指定的日志文件中，选择console会将日志输出到标准输出，当然也可以两者同时选择
  RollingPolicy: daily                          # rotate依据，可选的有：daily, size。如果选daily则根据天进行转存，如果是size则根据大小进行转存
  RotateDate: 1                                 # rotate转存时间，配合rollingPolicy: daily使用
  RotateSize: 1                                 # rotate转存大小，配合rollingPolicy: size使用
  BackupCount: 7                                # 当日志文件达到转存标准时，log系统会将该日志文件进行压缩备份，这里指定了备份文件的最大个数。
  File: storage/logs/fwds.log                   # 日志文件 普通
  WarnFile: storage/logs/fwds.warn.log          # 日志文件 告警
  ErrorFile: storage/logs/fwds.err.log          # 日志文件 错误

Jwt:
  JwtSecret: Rtg9BPKNE62mB4mgvK9NGPZvQSaJWNxijxR42qRgq0iBv5
  JwtDuration: 2                 # token 有效时长，单位小时

HashIds:
  Secret: "fwds"
  Length: 12

Email:
  Host: SMTP_HOST         # SMTP地址
  Port: 25                # 端口
  Username: USER          # 用户名
  Password: PASSWORD      # 密码
  Name: fwds              # 发送者名称
  Address: SEND_EMAIL     # 发送者邮箱
  ReplyTo: EMAIL          # 回复地址
  Keepalive: 30           # 连接保持时长

#钉钉
DingTalk:
  err: #错误群
    Url: ""
    Secret: ""

#短信
Sms:
  Use: "AliYun"
  Tencent:
    SecretId: ""
    SecretKey: ""
    SdkAppId: ""
    Business:
      Panic:
        SignName: ""
        TemplateId: ""
  AliYun:
    AccessKey: ACCESS_KEY
    SecretKey: SECRET_KEY
    RegionId: RegionId
    Business:
      Panic:
        SignName: ""
        TemplateId: ""

Oss:
  AliYun:
    AccessKey:
    SecretKey:
    Bucket:
    Endpoint:

Mq:
  Switch: false
  Use: "Nsq"
  RocketMqAli:
    AccessKey:
    SecretKey:
    Endpoint:
    InstanceId:
  RocketMq:
    Endpoint:
  Nsq:
    Endpoint: "127.0.0.1:4150"
  Business: #业务相关
    Test:
      Name: "测试"
      Topic: "test"
      tag: "test"
      GroupId: "GID_test"


Trace:
  ServiceName: "fwds"                                          # 服务名
  Open: true
  TraceAgent: "jaeger"

Jaeger: #Jaeger配置
  SamplingServerURL: "http://127.0.0.1:5778/sampling"
  SamplingType: "const"
  SamplingParam: "1.0"
  LocalAgentHostPort: "127.0.0.1:6831"
  Propagation: "jaeger"
  Gen128Bit: true
  TraceContextHeaderName: "uber-trace-id"
  CollectorEndpoint: ""
  CollectorUser: ""
  CollectorPassword: ""

Etcd:
  Host: "http://127.0.0.1:4001"
  SecretKey: "http://127.0.0.1:4001"
  ConfigPath: "/config/config.yaml"


#告警通知
Notify:
  Panic:
    Email: ""
    Sms: ""
    DingTalk: "err"